package com.yuyz.pojo;

import java.util.Date;

public class Emp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.id
     *
     * @mbg.generated Wed Sep 16 20:03:10 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.username
     *
     * @mbg.generated Wed Sep 16 20:03:10 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.dept_id
     *
     * @mbg.generated Wed Sep 16 20:03:10 CST 2020
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.create_date
     *
     * @mbg.generated Wed Sep 16 20:03:10 CST 2020
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.id
     *
     * @return the value of emp.id
     *
     * @mbg.generated Wed Sep 16 20:03:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.id
     *
     * @param id the value for emp.id
     *
     * @mbg.generated Wed Sep 16 20:03:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.username
     *
     * @return the value of emp.username
     *
     * @mbg.generated Wed Sep 16 20:03:10 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.username
     *
     * @param username the value for emp.username
     *
     * @mbg.generated Wed Sep 16 20:03:10 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.dept_id
     *
     * @return the value of emp.dept_id
     *
     * @mbg.generated Wed Sep 16 20:03:10 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.dept_id
     *
     * @param deptId the value for emp.dept_id
     *
     * @mbg.generated Wed Sep 16 20:03:10 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    @Override
    public String toString() {
        return "Emp{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", deptId=" + deptId +
                ", createDate=" + createDate +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.create_date
     *
     * @return the value of emp.create_date
     *
     * @mbg.generated Wed Sep 16 20:03:10 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.create_date
     *
     * @param createDate the value for emp.create_date
     *
     * @mbg.generated Wed Sep 16 20:03:10 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}